### PR TITLE
Remove duplicate SSIDs from setup web page

### PR DESCRIPTION
**Pull request by Avi0n**
If there are multiple APs broadcasting the same SSID (such as mesh setups), duplicate SSIDs show up in the WiFi setup dropdown. This PR fixes this by only displaying the network that has the strongest signal.
There's no directly associated issue, but [this comment ](https://github.com/ratgdo/homekit-ratgdo/issues/36#issuecomment-1858448789) mentions the problem.

### CODE REVIEW

**Comment by Avi0n** [comment]
Here's a slightly different version using `std::sort` instead of `swap` if preferred.
https://github.com/Avi0n/homekit-ratgdo/commit/ccf3b38b1b9352b3e0ff2ae2948122e8306794d2

**Comment by thenewwazoo** [comment]
It looks like the esphome implementation does [something similar](https://github.com/esphome/esphome/blob/0a117eb562204a28d1955aa8eb6d2963c625d95a/esphome/components/improv_serial/improv_serial_component.cpp#L223) but without the RSSI preference. Do you see the same thing?

**Comment by Avi0n** [comment]
I hadn't seen esphome's implementation, but yes that's what I'm seeing as well.

I'd like to keep the RSSI sorting for cases where the strong network gets cut, because the device could have a hard time connecting if the signal is weak. Most networks with multiple APs have Client Steering enabled, but if they don't, the device would continually try to connect to the weaker AP due to storing the BSSID of the weaker AP it initially connected to.

**Comment by dkerr64** [comment]
Is it possible to allow user to manually enter SSID name?  If a SSID name is not broadcast then it will not show up.  Some network SSIDs are deliberately hidden from broadcasting but can still be connected to if you enter it manually.

**Comment by jgstroud** [comment]
That's certainly a very useful feature, but I think it's unrelated to this PR. Should open a separate issue for that

**Pull request merged**
