### PR TITLE
Add initial skeleton

### PR DESCRIPTION
**Pull request by thenewwazoo**
This commit adds a basic skeleton for a HomeKit garage door opener accessory. It has been tested on a real device.

The following log illustrates testing on my phone:
```
--- Terminal on /dev/cu.usbserial-A501UYUE | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp8266_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
........................................
WiFi connected, IP: 192.168.1.115
>>> [  25803] HomeKit: Update the CPU to run at 160MHz
>>> [  25811] HomeKit: Starting server
>>> [  25815] HomeKit: Using existing accessory ID: 63:16:03:16:49:C0
>>> [  25821] HomeKit: Found admin pairing with 06AD472B-025D-4EDF-9281-9E2937611E33, disabling pair setup
>>> [  25830] HomeKit: Configuring MDNS
>>> [  25835] HomeKit: MDNS begin: Garage Door, IP: 192.168.1.115
>>> [  25842] HomeKit: Init server over

Setting up pins
>>> [  25846] HomeKit: Setting up comms

RATGDO setup end
>>> [  28038] HomeKit: Got new client: local 192.168.1.115:5556, remote 192.168.1.174:49822
>>> [  28047] HomeKit: [Client 1073680452] Pair Verify Step 1/2
>>> [  28537] HomeKit: Free heap: 41872
>>> [  28644] HomeKit: [Client 1073680452] Pair Verify Step 2/2
>>> [  28651] HomeKit: [Client 1073680452] Found pairing with 06AD472B-025D-4EDF-9281-9E2937611E33
>>> [  28680] HomeKit: Call ge_double_scalarmult_vartime_lowmem in ge_low_mem.c
>>> [  30122] HomeKit: [Client 1073680452] Verification successful, secure session established
>>> [  30130] HomeKit: Free heap: 41984
>>> [  30179] HomeKit: [Client 1073680452] Get Accessories
>>> [  30205] HomeKit: get current door state: 0
>>> [  30210] HomeKit: get target door state: 0
>>> [  30215] HomeKit: get obstruction: 0
>>> [  30288] HomeKit: [Client 1073680452] Update Characteristics
>>> [  30340] HomeKit: [Client 1073680452] Get Characteristics
>>> [  35492] HomeKit: [Client 1073680452] Get Characteristics
>>> [  40581] HomeKit: [Client 1073680452] Update Characteristics
>>> [  40614] HomeKit: [Client 1073680452] Get Characteristics
>>> [  40623] HomeKit: get target door state: 0
>>> [  40627] HomeKit: get current door state: 0
>>> [  40631] HomeKit: get obstruction: 0
>>> [  40670] HomeKit: [Client 1073680452] Get Characteristics
>>> [  40693] HomeKit: [Client 1073680452] Get Characteristics
>>> [  41458] HomeKit: [Client 1073680452] Get Characteristics
>>> [  41467] HomeKit: get obstruction: 0
>>> [  41471] HomeKit: get target door state: 0
>>> [  41475] HomeKit: get current door state: 0
>>> [  42073] HomeKit: [Client 1073680452] Get Characteristics
>>> [  42082] HomeKit: get current door state: 0
>>> [  43472] HomeKit: [Client 1073680452] Update Characteristics
>>> [  43480] HomeKit: set door state: 1
>>> [  43483] HomeKit: [Client 1073680452] Got characteristic 1.11 change event
>>> [  43490] HomeKit: TODO: close door

>>> [  43494] HomeKit: [Client 1073680452] Got characteristic 1.10 change event
>>> [  53939] HomeKit: [Client 1073680452] Update Characteristics
>>> [  53947] HomeKit: set door state: 0
>>> [  53951] HomeKit: [Client 1073680452] Got characteristic 1.11 change event
>>> [  53958] HomeKit: TODO: open door
```

### CODE REVIEW

**Comment by thenewwazoo** [comment]
I'll test this on real (non-ratgdo) hardware tomorrow. The goal is simply to get a "dummy" device working and showing up in HomeKit. Once that's done, I'll merge and start working on the comms code while I wait for my real ratgdo device to arrive.

**Comment by PaulWieland** [comment]
Looking forward to testing this. Do you know how to implement improv for ESP Web Serial?

**Comment by thenewwazoo** [comment]
> Looking forward to testing this. Do you know how to implement improv for ESP Web Serial?

I do - I probably won’t use the same bootstrap library just to avoid bringing in unrelated mqtt code , but there’s an off the shelf library that is easy to integrate.

**Comment by PaulWieland** [comment]
okay great. And yeah, I wouldn't suggest using the bootstrap library either. I will eventually migrate away from it for the mqtt version.

**Comment by thenewwazoo** [comment]
Okay, I've gotten this running on an old ESPresso Lite v2.0 I had lying around, and it functions as a "dummy" garage door. It's _basically_ just an example HomeKit project at this point.

I'm going to merge it and start working on the Improv stuff while I wait for my real hardware to arrive. Once that's here, I'll start on porting over the Security+ 2.0 code from the ESPhome codebase.

**Comment by PaulWieland** [comment]
The esphome code base is not up to date. Use the [secplus 1.0 branch](https://github.com/paulWieland/ratgdo/tree/2.0-secplus1.0) from my repo which is where all new features and improvements are added. I'll be moving it to this group as soon as I have a chance.

**Pull request merged**
