### PR TITLE
Add discord release notification

### PR DESCRIPTION
**Pull request by donavanbecker**
Screenshot 2024-01-04 at 7 12 12 PM

### CODE REVIEW

**Comment by donavanbecker** [comment]
@PaulWieland can you add the discord webhook url as an action secret in settings of this repo?

**Comment by PaulWieland** [comment]
I added this secret and set the value to the string that was in the commit for webhook_url, let me know if it works.

image

**Comment by donavanbecker** [comment]
Awesome! Thanks! I will update the commit

**Comment by donavanbecker** [comment]
@thenewwazoo or @jgstroud this is now ready.

**Comment by jgstroud** [comment]
Fantastic!  Another great additions @donavanbecker

**Pull request merged**
