### PR TITLE
Placeholder for next release.

### PR DESCRIPTION
**Pull request by dkerr64**
Collection of features / bug fixes for next release.

### CODE REVIEW

**Comment by dkerr64** [comment]
@jgstroud @donavanbecker I am ready to merge this and tag a pre-release for testing.  Here is what is in the changelog...

* Bugfix... alignment of minHeap and minStack was wrong on chrome browsers.
* Bugfix... set WiFi hostname based on user provided device name.
* Bugfix... also set the browser page title to the user provided device name.
* New feature... allow user to set custom username for the webpage.
* New feature... allow user to set static IP address.
* New feature... add new system logs page (opens in new browser tab).
* New feature... add spinning page-loading icon to provide feedback on slow network links
* New feature... add option to obtain real time from NTP sever
* Cleanup... consolidated all code for retrieving user configured settings into one file (utilities.cpp).

Okay to proceed?

Thanks

**Comment by jgstroud** [comment]
I can build and load this PR before you merge if you want.

**Comment by donavanbecker** [comment]
I have built and installed this PR on my ratgdo, all working good!

**Comment by jgstroud** [comment]
Go ahead and merge it then.  Turns out I am once again more busy today than I planned to be.  Since we have 1 independent confirmation, I'm good with merging.

**Pull request merged**
