### PR TITLE
prevent continuous logging when transmit fails

### PR DESCRIPTION
**Pull request by kharamel**
Resolves https://github.com/ratgdo/homekit-ratgdo/issues/27

I only tested this using Serial Monitor. Didn't seem to need implement 2nd option on https://github.com/ratgdo/homekit-ratgdo/issues/27#issuecomment-1857603126

### CODE REVIEW

**Comment by SausCode** [comment]
I believe at startup prev and current will likely be the same value, which means it will not update the status. I think on the first call to this function you will always want to force an update. Say for instance door is obstructed, esp loses power, obstruction cleared, power restored, status is not updated correctly.

**Comment by jgstroud** [comment]
Why are we adding obstruction status in the comms module?

**Comment by jgstroud** [comment]
I think you are confusing transmit collisions with obstructions.

**Comment by jgstroud** [comment]
To resolve #27 you need to remove all the obstruction stuff you added and you just need a single static variable to track the previous collision state and output the log message on collision change.

**Comment by kharamel** [comment]
Made modifications based on feedback above.

**Comment by jgstroud** [comment]
Can you edit the name of this PR and squash your commits?

**Comment by jgstroud** [comment]
The log_coll_error variable seems to use inverse logic.  It's true when there is no error. You should invert it

**Comment by kharamel** [comment]
log_coll_error indicates we want to log error. We don't want to do that unless we have had successful transmission since we last logged the error. Based on that, don't we want what's implemented here?

**Comment by edrikk** [comment]
The name of the log_coll_* variables are not really good in my opinion.
Once/if this PR is accepted the concept of "collision" will be lost and people will have to read the code to see what it means .. "log collect error" maybe?

I would suggest being a bit more verbose in this case with the name, and given that it's a true / false even add _ind to them.
e.g. log_collision_err_ind and log_collision_info_ind

**Comment by jgstroud** [comment]
I definitely agree.  The variable names are odd and have nothing to do with the collision.  It's also confusing logic to set the error flag true after a successful transmit. 

I'm also not sure we really need the 2 different log messages and variables.

**Comment by kharamel** [comment]
In my opinion given the context, coll in variable name was enough to indicate collision. However, I've update the variable name to be more verbose. Also, the variable was not an error flag but a flag that indicated if the error needed to be logged. I've made change for that to be more clear by changing it to indicate if the error was logged. From my understanding, we retry to transmit only from comms_loop. I think It makes sense to log `...will retry` there. Since comms_loop is not the only one calling transmit, having a single variable to handle logging in both places would cause interference.

**Comment by jgstroud** [comment]
This reads so much better.  I think it's ok like this.  Also, you misunderstood my other comment, or I just wasn't clear.  I think it would just be more simple if we remove the RERROR("transmit failed" message all together along with the new variable and just leave the collision detected message in the transmit function.  Not sure what good it does to have the 2 messages, especially when we don't log an error for the other calls to the transmit function.  Also removes some extra unnecessary instructions.

**Comment by kharamel** [comment]
That makes sense. I didn't want to discount any reasoning the author might have had when implementing it. @thenewwazoo any objections to getting rid of this [line](https://github.com/ratgdo/homekit-ratgdo/blob/main/src/comms.cpp#L228)?

**Comment by thenewwazoo** [comment]
If I'm understanding correctly, the concern is that in a certain improper configuration (namely, a ratgdo that's unconnected to a garage door opener), the UX is bad. I'm receptive to that, but I think this is PR slightly misses (or doesn't clearly define) the desired outcome in that case, and perhaps conflates that with normal collisions.

Bus contention is normal and expected, and having its occurrence logged is (probably) a useful thing when diagnosing problems in a properly-installed ratgdo. I'd prefer to define how to detect error conditions that result in repeated bus collisions, and then act on that. Improving the UX in the case of improper configuration/installation would fall out naturally as a result.

I don't think exponential backoff makes sense because multiple subsequent collisions definitely indicates a problem we don't want to work around (or that we expect to resolve itself). An initial thought is setting an error-condition status bit and refusing to transmit again, but I'm open to suggestions.

**Comment by jgstroud** [comment]
I just loaded up a new ratgdo and it's sitting on my bench not connected to anything and I do not see this logging loop.  Seems like we are solving sort of a Don't Care scenario?  Now I'm thinking more about this and as collisions will happen under normal operation, but they should not be continuously happening back to back, so having this log message printing every time we have a collision would indicate that something is clearly wrong.

I think maybe we just leave this PR alone and leave the issue as working as designed.   If we decide to log to flash, then we'll need to revisit this or rate limit it somehow.

What are your thoughts @thenewwazoo ?

**Comment by jgstroud** [comment]
As I've been messing around with testing on a unit not connected, I have hit this issue.  But for that benchtop testing, I just remove the check and let it transmit the packet.  In normal operation this shouldn't be happening, and the continuous log messages are an indicator that something is broken in your setup.  I think we should just close this without merging and close the issue as working as designed.

**Pull request closed without merging**
